# Generated by Django 2.1.7 on 2019-04-01 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CTest', '0002_test_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='available_time',
            field=models.TimeField(default=datetime.time(0, 10)),
        ),
    ]
