# Generated by Django 2.1.7 on 2019-03-22 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_status', models.CharField(choices=[(1, 'student'), (2, 'teacher'), (3, 'Not Defined')], default=1, max_length=1)),
            ],
        ),
    ]
