# Generated by Django 2.1.7 on 2019-03-22 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Department', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_first_name', models.CharField(default='', max_length=1024)),
                ('teacher_last_name', models.CharField(default='', max_length=1024)),
                ('teacher_email', models.CharField(blank=True, default='', max_length=1024, null=True)),
                ('teacher_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Department.Department')),
                ('teacher_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
