# Generated by Django 2.1.7 on 2019-03-20 06:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Essentials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentContactDetailsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFamilyDetailsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StudentGeneralProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSummaryModel',
            fields=[
                ('studentRollNumber', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('student_first_name', models.CharField(default='', max_length=256)),
                ('student_last_name', models.CharField(default='', max_length=256)),
                ('student_dob', models.DateField()),
                ('student_gender', models.CharField(max_length=256)),
                ('student_father_first_name', models.CharField(default='', max_length=256)),
                ('student_father_last_name', models.CharField(default='', max_length=256)),
                ('student_mother_first_name', models.CharField(default='', max_length=256)),
                ('student_mother_last_name', models.CharField(default='', max_length=256)),
                ('student_mobile', models.CharField(default=0, max_length=10, validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(10)])),
                ('student_emergency_contact', models.CharField(default=0, max_length=10, validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(10)])),
                ('student_phone_contact', models.CharField(blank=True, max_length=10, null=True)),
                ('student_caste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Essentials.CategoryCasteModel')),
                ('student_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
