# Generated by Django 2.1.7 on 2019-03-23 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CTest', '0001_initial'),
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_permitted', models.CharField(choices=[(1, 'not-permitted'), (2, 'requested'), (3, 'permitted')], default=1, max_length=2)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.StudentSummaryModel')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CTest.Test')),
            ],
        ),
    ]
