# Generated by Django 2.1.7 on 2019-03-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_auto_20190320_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsummarymodel',
            name='student_caste',
            field=models.CharField(choices=[('GEN', 'General or Open'), ('OBC', 'Other backward classes'), ('SC', 'Scheduled Caste'), ('ST', 'Scheduled Tribe')], default='GEN', max_length=3),
        ),
    ]
