# Generated by Django 2.1.7 on 2019-03-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_studenttestmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttestmodel',
            name='student_score',
            field=models.IntegerField(default=-1),
        ),
    ]
