# Generated by Django 2.1.7 on 2019-03-23 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CTest', '0001_initial'),
        ('Student', '0003_studenttestmodel_student_score'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studenttestmodel',
            unique_together={('student_id', 'test_id')},
        ),
    ]
