# Generated by Django 2.1.7 on 2019-03-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_auto_20190323_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttestmodel',
            name='is_permitted',
            field=models.CharField(choices=[(1, 'not-permitted'), (2, 'requested'), (3, 'permitted')], default=2, max_length=2),
        ),
    ]
