# Generated by Django 2.1.7 on 2019-04-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0007_studenttestmodel_test_attempt_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsummarymodel',
            name='student_email',
            field=models.CharField(default='', max_length=256),
        ),
    ]
