# Generated by Django 2.1.7 on 2019-03-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(default='', max_length=1024)),
                ('department_code', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
